### PR TITLE
componentWillReceiveProps to getDerivedStateFromProps

### PR DESCRIPTION
**Pull request by wanderbon**

### CODE REVIEW

**Comment by IntelliJAbhishek** [comment]
You can't use `this` inside static method.

**Comment by IntelliJAbhishek** [comment]
@wanderbon  You can't use `this` inside `static` method.

**Comment by wanderbon** [comment]
@IntelliJAbhishek

Thanks, got rid of the getDerivedStateFromProps.

**Comment by ninjaengineers** [comment]
Can't wait to get this merged.

**Comment by jtibbertsma** [comment]
So I tested it out, and this pull request breaks transitions. To make transitions work, the new styles have to be intercepted _before_ the component rerenders in order to set up a smooth transition to the new styles. You can't just throw everything in `componentDidUpdate` and expect it to work. The solution will have to use some combination of `getDerivedStateFromProps` and `componentDidUpdate`.

I'll give it a shot, though. I'm sick of the constant warnings in my app

**Comment by oblador** [comment]
@jtibbertsma Help would be greatly appreciated, thx :-)

**Comment by AfrazHussain** [comment]
Hey, does anyone have any information on when this PR will be merged? If no one has worked on the requested changes, I can give it a shot ASAP.

P.S. If anyone is looking to disable YellowBox warnings just for the time being they can use `YellowBox.ignoreWarnings([])`.

**Comment by fri0z** [comment]
Who knows when PR will accept ?

**Comment by wilforlan** [comment]
@oblador @oliverdolgener please guys, what is stoping this PR?

**Comment by oblador** [comment]
I will look more into this one later, but for now you can use [1.3.3](https://github.com/oblador/react-native-animatable/releases/tag/v1.3.3) to remove the warning.

**Comment by jtibbertsma** [comment]
@wilforlan
This pull request breaks features of this library

**Comment by esdotzed** [comment]
any updates on this?

**Comment by oblador** [comment]
Closing this PR, warning is gone for now and it breaks functionality.

**Pull request closed without merging**
