### PR TITLE
update onAnimationEnd when props.onAnimationEnd updated

### PR DESCRIPTION
**Pull request by erichua23**
When I set `delay` to my `Animatable.View`, duration this delay, i update the `props.onAnimationEnd`. The change will not work, since the origin code does not use the new `onAnimationEnd`.

this PR fix it

### CODE REVIEW

**Comment by jeveloper** [comment]
@oblador  Hey Joel, do you think this can be merged?

**Comment by oblador** [comment]
Fixed in [1.3.0](https://github.com/oblador/react-native-animatable/releases/tag/v1.3.0)

**Comment by jeveloper** [comment]
whoa !!

**Comment by oblador** [comment]
@jeveloper Miracles happen 😄 Sorry for the lead time here.

**Pull request closed without merging**
