### PR TITLE
Fix parameter name in shake() method

### PR DESCRIPTION
**Pull request by jndev**

### CODE REVIEW

**Comment by oblador** [comment]
Wouldn't this break it?

**Comment by jndev** [comment]
This fixes the following error: `Can't find variable: times` in `index.js @ 536:0`

**Comment by oblador** [comment]
Sorry misread the diff, thought you were changing it to `timesArg`. Thanks!

**Comment by jndev** [comment]
You're welcome. Thanks to you for this package!

**Comment by irfaan** [comment]
FYI - installing fresh from npm doesn't reflect this change.

**Comment by oblador** [comment]
@irfaan: Released in [0.6.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.6.1).

**Pull request merged**
