### PR TITLE
 Add changeable animationValue

### PR DESCRIPTION
**Pull request by zhuguoxi**
some times , I need a smaller motion animation, but this just depending on the layout or window ,so I add animationValue props,

### CODE REVIEW

**Comment by oblador** [comment]
Sorry, not following. Can you explain the use case here?

**Comment by zhuguoxi** [comment]
like this
`<View style={styles.route}  animation='fadeInLeft'  duration={200} animationValue={10}>
	<View style={styles.point}></View>
	<View style={styles.textbox}>
		<Text style={styles.routeText}>{text}</Text>
	</View>
</View>`

**Comment by oblador** [comment]
I still don't really understand what it achieves and why it's desirable.

**Comment by zhuguoxi** [comment]
t can set the range of motion, especially if I want to use a **small range** of animation；

**Comment by oblador** [comment]
Hmm, I've been planning custom animation support which I think is a better way to approach this. Just need the time to do it.. :-)

**Comment by zhuguoxi** [comment]
ok, good

**Comment by zhuguoxi** [comment]
hi ,how long it released

**Comment by oblador** [comment]
I have no ETA.

**Comment by oblador** [comment]
@zhuguoxi Here's custom animations finally: https://github.com/oblador/react-native-animatable/pull/67 I will close this PR for now :-)

**Pull request closed without merging**
