### PR TITLE
Rotate animation

### PR DESCRIPTION
**Pull request by aforty**
I realize that rotate can be done through the style `transform` property but it seems that when using that it doesn't take into account `iterationCount`. I essentially needed a rotate animation that repeated forever (for a loading indicator) and this seemed to be the easiest way to do that.

Hope this is helpful to others.

Thank you for the fantastic package!

### CODE REVIEW

**Comment by aforty** [comment]
Updated commits so this can be merged again. Is there a reason it hasn't yet?

**Comment by oblador** [comment]
Sorry, no not really. Care to update readme and example?

**Comment by aforty** [comment]
Looks like it was already in the example under attention seekers, added to same place in README.

Thanks!

**Comment by oblador** [comment]
Awesome, thanks! In future releases I'd like to support custom animations which would solve this use case. But until then this is super useful 👍

**Comment by aforty** [comment]
Awesome, thanks a lot!

**Comment by oblador** [comment]
Released in [0.6.1](https://github.com/oblador/react-native-animatable/releases/tag/v0.6.1).

**Pull request merged**
