### PR TITLE
Migrate deprecated React.PropTypes

### PR DESCRIPTION
**Pull request by alphasp**

### CODE REVIEW

**Comment by corymsmith** [comment]
Should probably also update the Example as well: https://github.com/oblador/react-native-animatable/blob/101582abc1eeae06a640f229b6a89641bc7e34ca/Example/cell.js#L1

**Comment by iRoachie** [comment]
@alphasp Just sent you a pr to complete the changes

**Comment by alphasp** [comment]
@iRoachie thanks for pointing out my mistake. I had merged your PR with my PR.

**Comment by iRoachie** [comment]
Awesomene! We just have to wait on @oblador

**Comment by iRoachie** [comment]
@oblador Can you take a look at this?

**Comment by oblador** [comment]
Yes, sorry been on vacation the last month so updates are slow 😺

**Comment by oblador** [comment]
Released in [1.2.3](https://github.com/oblador/react-native-animatable/releases/tag/v1.2.3).

**Comment by iRoachie** [comment]
Ha enjoy yourself man! Maybe put like small [on vacation] badge on the readme :D

**Pull request merged**
